CREATE TABLE [dbo].[Event]
(
    [Id] INT NOT NULL IDENTITY,
    [SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
    [Topic] VARCHAR(150) NULL,
    [Client] VARCHAR(150) NULL,
    [Address1] VARCHAR(150) NULL,
    [Address2] VARCHAR(150) NULL,
    [City] VARCHAR(150) NULL,
    [State] VARCHAR(150) NULL,
    [Zip] VARCHAR(150) NULL,
    [StartDate] DATETIME2 NOT NULL,
    [EndDate] DATETIME2 NOT NULL,
    [CreatingUser] VARCHAR(150) NOT NULL,
    [CreateDate] DATETIME2 NOT NULL,
    [UpdatingUser] VARCHAR(150) NULL,
    [UpdateDate] DATETIME2 NULL,
    CONSTRAINT [PK_Event] PRIMARY KEY ([Id]),
    PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[dbo].[Event_HISTORY], DATA_CONSISTENCY_CHECK=ON))
